import os
from dotenv import load_dotenv

load_dotenv()

class Config:
    """Configuration class for environment variables"""
    
    # Twitter authentication
    TWITTER_AUTH_TOKEN = os.getenv('TWITTER_AUTH_TOKEN')
    
    # Discord configuration
    DISCORD_TOKEN = os.getenv('DISCORD_TOKEN')
    DISCORD_WEBHOOK_URL = os.getenv('DISCORD_WEBHOOK_URL')
    
    # Application settings
    DEFAULT_LIMIT = int(os.getenv('DEFAULT_LIMIT', 100))
    DEFAULT_FILENAME = os.getenv('DEFAULT_FILENAME', 'hasil_crawling.csv')
    DEFAULT_SEARCH_QUERY = os.getenv('DEFAULT_SEARCH_QUERY', 'from:tanyakanrl lang:id until:2024-10-29 since:2024-10-01')
    
    # Slang dictionary
    SLANG_DICT = {
      'wkwkwkkwkw': 'tertawa',
      'elu': 'kamu',
      'skrng': 'sekarang',
      'banyk': 'banyak',
      'bgt': 'banget',
      'kalo': 'kalau',
      'yg': 'yang',
      'mo': 'mau',
      'brapa': 'berapa',
      'ga': 'tidak',
      'udah': 'sudah',
      'lg': 'lagi',
      'kuy': 'yuk',
      'gans': 'ganteng',
      'cans': 'cantik',
      'santuy': 'santai',
      'mager': 'malas gerak',
      'baper': 'bawa perasaan',
      'gabut': 'gaji buta',
      'japri': 'jaringan pribadi',
      'kepo': 'ingin tahu',
      'pansos': 'panjat sosial',
      'receh': 'murah',
      'bucin': 'budak cinta',
      'ambyar': 'hancur',
      'mantul': 'mantap betul',
      'garing': 'tidak lucu',
      'halu': 'halusinasi',
      'bokap': 'ayah',
      'nyokap': 'ibu',
      'doi': 'kekasih',
      'lebay': 'berlebihan',
      'alay': 'berlebihan',
      'songong': 'sombong',
      'norak': 'kampung',
      'cupu': 'culun',
      'jempol': 'bagus',
      'sabi': 'bisa',
      'woles': 'santai',
      'goks': 'gokil',
      'kece': 'keren',
      'kacau': 'buruk',
      'parah': 'sangat',
      'bokis': 'bohong',
      'ngakak': 'tertawa terbahak-bahak',
      'julid': 'iri dengki',
      'mami': 'ibu',
      'papi': 'ayah',
      'bestie': 'sahabat',
      'salfok': 'salah fokus',
      'komuk': 'kondisi muka',
      'curhat': 'curahan hati',
      'asem': 'asam',
      'beud': 'banget',
      'bingit': 'banget',
      'cabe': 'anak muda nakal',
      'cager': 'keren',
      'caper': 'cari perhatian',
      'ceban': 'sepuluh ribu',
      'cengli': 'adil',
      'ciamik': 'bagus',
      'cincau': 'biasa saja',
      'ciyus': 'serius',
      'cowok': 'laki-laki',
      'cuy': 'teman',
      'demen': 'suka',
      'doi': 'pacar',
      'ebok': 'ibu',
      'egp': 'emang gue pikirin',
      'encok': 'pegal',
      'engap': 'sesak',
      'gaber': 'tidak bergairah',
      'gadun': 'lelaki hidung belang',
      'gebetan': 'orang yang disukai',
      'geje': 'tidak jelas',
      'gengges': 'mengganggu',
      'gokil': 'lucu',
      'gremet': 'gemas',
      'ilah': 'masya allah',
      'ilfeel': 'ilang feeling',
      'jamet': 'jajal metal',
      'jayus': 'tidak lucu',
      'jomblo': 'tidak punya pacar',
      'kabor': 'kabur',
      'kagak': 'tidak',
      'kamsia': 'terima kasih',
      'kapok': 'jera',
      'kasmaran': 'jatuh cinta',
      'katro': 'kampungan',
      'kecentilan': 'genit',
      'kesbek': 'cashback',
      'kesel': 'kesal',
      'kezel': 'kesal',
      'kicep': 'diam',
      'kiyowo': 'lucu',
      'koncian': 'pacar rahasia',
      'koplak': 'bodoh',
      'kucluk': 'bodoh',
      'kudet': 'kurang update',
      'kzl': 'kesal',
      'letoy': 'lemas',
      'machoo': 'maco',
      'maksi': 'makan siang',
      'mami': 'ibu',
      'mandul': 'tidak subur',
      'manis': 'cantik',
      'mblangsak': 'susah',
      'mehong': 'mahal',
      'mepet': 'dekat',
      'merinding': 'takut',
      'miskom': 'miskomunikasi',
      'mokad': 'mati',
      'molor': 'tidur',
      'mulus': 'cantik',
      'mumet': 'pusing',
      'narsis': 'percaya diri berlebihan',
      'ndas': 'kepala',
      'ngeh': 'sadar',
      'ngehek': 'kurang ajar',
      'ngek': 'terkejut',
      'ngelenong': 'berakting',
      'ngemil': 'makan ringan',
      'ngocol': 'lucu',
      'ngok': 'terkejut',
      'ngondek': 'banci',
      'ngongrong': 'makan banyak',
      'ngopilah': 'minum kopi',
      'ngotot': 'keras kepala',
      'ngowoh': 'terbuka',
      'ngoyo': 'bekerja keras',
      'ngepet': 'mencuri',
      'nyablak': 'berbicara sembarangan',
      'nyak': 'ibu',
      'nyantai': 'santai',
      'nyari': 'mencari',
      'nyengir': 'tersenyum',
      'nyok': 'yuk',
      'nyokap': 'ibu',
      'pala': 'kepala',
      'pakboi': 'playboy',
      'palbis': 'paling bisa',
      'palelu': 'kepalamu',
      'pamer': 'memamerkan',
      'papi': 'ayah',
      'pegel': 'pegal',
      'pekoks': 'bodoh',
      'pelakor': 'perebut laki orang',
      'pencitraan': 'citra palsu',
      'pencopet': 'pencuri',
      'pengen': 'ingin',
      'perek': 'pelacur',
      'pergok': 'terlihat',
      'perkedel': 'bodoh',
      'php': 'pemberi harapan palsu',
      'pijit': 'pijat',
      'pipis': 'buang air kecil',
      'plesbek': 'flashback',
      'pongah': 'sombong',
      'porotin': 'memeras',
      'prank': 'lelucon',
      'rempong': 'ribet',
      'rese': 'menyebalkan',
      'ribet': 'sulit',
      'rontok': 'jatuh',
      'sangit': 'bau sangit',
      'saru': 'tidak senonoh',
      'sawer': 'memberi uang',
      'say': 'sayang',
      'segel': 'baru',
      'segmen': 'bagian',
      'semok': 'montok',
      'sepik': 'menggombal',
      'sianida': 'racun',
      'sikat': 'makan',
      'sikil': 'kaki',
      'sikon': 'situasi dan kondisi',
      'sipil': 'biasa',
      'sirik': 'iri',
      'sotoi': 'sok tahu',
      'sowan': 'berkunjung',
      'spokat': 'sepatu',
      'sruntulan': 'sembarangan',
      'stok': 'persediaan',
      'sumpek': 'sesak',
      'tajir': 'kaya',
      'tampol': 'menampar',
      'tante': 'wanita dewasa',
      'tapir': 'kaya',
      'tegang': 'takut',
      'telmi': 'telat mikir',
      'tengil': 'nakal',
      'tepok': 'lemas',
      'tercyduk': 'tertangkap',
      'terong': 'laki-laki kemayu',
      'toyor': 'memukul kepala',
      'trepes': 'datar',
      'unyu': 'lucu',
      'uyee': 'asyik',
      'wakwaw': 'kacau',
      'yogs': 'asyik',
      'za': 'saja',
      'asemeleh': 'bagus',
      'badai': 'cantik',
      'cakep': 'ganteng',
      'canggih': 'pintar',
      'cemen': 'penakut',
      'cengeng': 'mudah menangis',
      'cihuy': 'asyik',
      'culun': 'bodoh',
      'edan': 'gila',
      'gahoel': 'gaul',
      'gile': 'gila',
      'gondes': 'gondrong ndeso',
      'gumoh': 'muntah',
      'kampret': 'mengagetkan',
      'kebelet': 'ingin buang air',
      'kocak': 'lucu',
      'ndeso': 'kampungan',
      'ngocol': 'lucu',
      'ngoplos': 'mencampur minuman',
      'ngiler': 'tertarik',
      'nyengir': 'tersenyum',
      'palelu': 'kepalamu',
      'prikitiw': 'ekspresi senang',
      'tajir': 'kaya',
      'udik': 'kampungan',
    }
    
    @classmethod
    def validate_config(cls):
        """Validate that required environment variables are set"""
        required_vars = ['TWITTER_AUTH_TOKEN', 'DISCORD_TOKEN']
        missing_vars = [var for var in required_vars if not getattr(cls, var)]
        
        if missing_vars:
            raise ValueError(f"Missing required environment variables: {', '.join(missing_vars)}")
        
        print("✓ Configuration validated successfully")

Config.validate_config()